import { ThemeConfig } from './themeConfig';

// 默认主题
export const defaultTheme: ThemeConfig = {
  id: '默认',
  name: '默认',
  description: '明亮活泼的默认主题',
  font: {
    family: 'Inter, Arial, sans-serif',
    size: 15,
    lineHeight: 1.7,
    weight: 500,
  },
  colors: {
    primary: '#ff4081',
    secondary: '#2196f3',
    accent: '#ffeb3b',
    text: '#2c3e50',
    background: '#ffffff',
    border: 'rgba(255, 64, 129, 0.2)',
  },
  spacing: {
    padding: 24,
    margin: 12,
    borderRadius: 16,
  },
  background: {
    type: 'gradient',
    gradientDirection: 135,
    gradientStart: '#ffecd2',
    gradientEnd: '#fcb69f',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(255, 64, 129, 0.3)',
    blur: 20,
    spread: 0,
    offsetX: 0,
    offsetY: 8,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      overflow: 'hidden',
      '&::before': {
        content: '""',
        position: 'absolute',
        top: '-20px',
        left: '-20px',
        width: '80px',
        height: '80px',
        background: 'linear-gradient(45deg, #ff4081, #2196f3)',
        clipPath: 'polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%)',
        zIndex: 1,
        animation: 'sparkle 3s ease-in-out infinite',
      },
      '&::after': {
        content: '"✨"',
        position: 'absolute',
        top: '-5px',
        right: '-5px',
        width: '40px',
        height: '40px',
        background: 'linear-gradient(135deg, #ffeb3b, #ff9800)',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '20px',
        zIndex: 1,
        animation: 'bounce 2s ease-in-out infinite',
      },
    },
    elements: {
      '.card-content': {
        position: 'relative',
        borderRadius: '16px',
        padding: '28px',
        background: 'rgba(255, 255, 255, 0.95)',
        border: '2px solid rgba(255, 64, 129, 0.2)',
        backdropFilter: 'blur(10px)',
        height: '100%',
        zIndex: 2,
        boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.6)',
      },
      '.md-blockquote': {
        borderLeft: '5px solid var(--card-color-primary)',
        padding: '1em 1.5em',
        margin: '1.5em 0',
        background: 'linear-gradient(90deg, rgba(255, 64, 129, 0.1), rgba(255, 64, 129, 0.05))',
        borderRadius: '0 8px 8px 0',
        color: '#555',
        fontStyle: 'italic',
      },
      '.md-strong': {
        color: 'var(--card-color-primary)',
        fontWeight: 700,
        textShadow: '0 1px 2px rgba(255, 64, 129, 0.2)',
      },
      '.md-em': {
        color: 'var(--card-color-secondary)',
        fontStyle: 'italic',
        background: 'linear-gradient(120deg, transparent 0%, rgba(33, 150, 243, 0.1) 50%, transparent 100%)',
      },
      '.md-hr': {
        border: 'none',
        height: '3px',
        background: 'linear-gradient(90deg, var(--card-color-primary), var(--card-color-secondary), var(--card-color-accent))',
        margin: '2em 0',
        borderRadius: '2px',
      },
      'h1, h2, h3': {
        background: 'linear-gradient(135deg, var(--card-color-primary), var(--card-color-secondary))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
      },
    },
  },
};

// 暗色主题
export const darkTheme: ThemeConfig = {
  id: '暗色',
  name: '暗色',
  description: '科技感十足的暗色主题',
  font: {
    family: 'JetBrains Mono, Consolas, monospace',
    size: 14,
    lineHeight: 1.8,
    weight: 400,
  },
  colors: {
    primary: '#00d4ff',
    secondary: '#ff0080',
    accent: '#00ff88',
    text: '#e0e6ed',
    background: '#0a0e1a',
    border: 'rgba(0, 212, 255, 0.3)',
  },
  spacing: {
    padding: 24,
    margin: 8,
    borderRadius: 8,
  },
  background: {
    type: 'gradient',
    gradientDirection: 225,
    gradientStart: '#0a0e1a',
    gradientEnd: '#1a1f2e',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(0, 212, 255, 0.4)',
    blur: 25,
    spread: 0,
    offsetX: 0,
    offsetY: 0,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      overflow: 'hidden',
      '&::before': {
        content: '""',
        position: 'absolute',
        top: '0',
        left: '0',
        width: '100%',
        height: '100%',
        background: 'radial-gradient(circle at 20% 20%, rgba(0, 212, 255, 0.1) 0%, transparent 50%), radial-gradient(circle at 80% 80%, rgba(255, 0, 128, 0.1) 0%, transparent 50%)',
        zIndex: 0,
      },
      '&::after': {
        content: '""',
        position: 'absolute',
        top: '-2px',
        left: '-2px',
        right: '-2px',
        bottom: '-2px',
        background: 'linear-gradient(45deg, #00d4ff, #ff0080, #00ff88, #00d4ff)',
        borderRadius: '10px',
        zIndex: -1,
        animation: 'neonBorder 3s linear infinite',
      },
    },
    elements: {
      '.card-content': {
        position: 'relative',
        borderRadius: '8px',
        padding: '28px',
        background: 'rgba(10, 14, 26, 0.95)',
        border: '1px solid rgba(0, 212, 255, 0.3)',
        backdropFilter: 'blur(20px)',
        height: '100%',
        color: 'var(--card-color-text)',
        zIndex: 1,
        boxShadow: 'inset 0 1px 0 rgba(0, 212, 255, 0.2), 0 0 20px rgba(0, 212, 255, 0.1)',
      },
      '.md-blockquote': {
        borderLeft: '4px solid var(--card-color-primary)',
        padding: '1em 1.5em',
        margin: '1.5em 0',
        background: 'rgba(0, 212, 255, 0.05)',
        borderRadius: '0 8px 8px 0',
        color: '#a0a9b8',
        position: 'relative',
        '&::before': {
          content: '"▶"',
          position: 'absolute',
          left: '8px',
          top: '50%',
          transform: 'translateY(-50%)',
          color: 'var(--card-color-primary)',
          fontSize: '12px',
        },
      },
      '.md-strong': {
        color: 'var(--card-color-primary)',
        fontWeight: 700,
        textShadow: '0 0 10px rgba(0, 212, 255, 0.5)',
        background: 'linear-gradient(90deg, var(--card-color-primary), var(--card-color-secondary))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
      },
      '.md-em': {
        color: 'var(--card-color-secondary)',
        fontStyle: 'italic',
        textShadow: '0 0 8px rgba(255, 0, 128, 0.3)',
      },
      '.md-hr': {
        border: 'none',
        height: '2px',
        background: 'linear-gradient(90deg, transparent, var(--card-color-primary), var(--card-color-secondary), var(--card-color-accent), transparent)',
        margin: '2em 0',
        borderRadius: '1px',
        boxShadow: '0 0 10px rgba(0, 212, 255, 0.3)',
      },
      'h1, h2, h3': {
        background: 'linear-gradient(135deg, var(--card-color-primary), var(--card-color-secondary), var(--card-color-accent))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
        textShadow: '0 0 20px rgba(0, 212, 255, 0.3)',
        position: 'relative',
        '&::after': {
          content: '""',
          position: 'absolute',
          bottom: '-4px',
          left: '0',
          width: '100%',
          height: '2px',
          background: 'linear-gradient(90deg, var(--card-color-primary), transparent)',
          borderRadius: '1px',
        },
      },
      'code': {
        background: 'rgba(0, 212, 255, 0.1)',
        color: 'var(--card-color-accent)',
        padding: '2px 6px',
        borderRadius: '4px',
        border: '1px solid rgba(0, 255, 136, 0.2)',
        fontFamily: 'JetBrains Mono, monospace',
      },
    },
  },
};

// 玻璃主题
export const glassTheme: ThemeConfig = {
  id: '玻璃',
  name: '玻璃',
  description: '透明玻璃质感主题',
  font: {
    family: 'SF Pro Display, Inter, Arial, sans-serif',
    size: 15,
    lineHeight: 1.6,
    weight: 300,
  },
  colors: {
    primary: '#007aff',
    secondary: '#5856d6',
    accent: '#ffffff',
    text: '#ffffff',
    background: 'transparent',
    border: 'rgba(255, 255, 255, 0.2)',
  },
  spacing: {
    padding: 28,
    margin: 8,
    borderRadius: 20,
  },
  background: {
    type: 'gradient',
    gradientDirection: 135,
    gradientStart: 'rgba(255, 255, 255, 0.1)',
    gradientEnd: 'rgba(255, 255, 255, 0.05)',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(0, 0, 0, 0.3)',
    blur: 40,
    spread: 0,
    offsetX: 0,
    offsetY: 20,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      overflow: 'hidden',
      background: 'linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05))',
      backdropFilter: 'blur(20px)',
      border: '1px solid rgba(255, 255, 255, 0.2)',
      '&::before': {
        content: '""',
        position: 'absolute',
        top: '0',
        left: '0',
        width: '100%',
        height: '1px',
        background: 'linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.8), transparent)',
        zIndex: 2,
      },
      '&::after': {
        content: '""',
        position: 'absolute',
        top: '20px',
        left: '20px',
        width: '60px',
        height: '60px',
        borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(255, 255, 255, 0.3) 0%, transparent 70%)',
        filter: 'blur(10px)',
        zIndex: 1,
      },
    },
    elements: {
      '.card-content': {
        position: 'relative',
        borderRadius: '20px',
        padding: '32px',
        background: 'rgba(255, 255, 255, 0.1)',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        backdropFilter: 'blur(30px)',
        height: '100%',
        color: 'var(--card-color-text)',
        zIndex: 2,
        boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.3), 0 0 30px rgba(0, 0, 0, 0.1)',
        '&::before': {
          content: '""',
          position: 'absolute',
          top: '0',
          left: '0',
          right: '0',
          height: '1px',
          background: 'linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.6), transparent)',
        },
      },
      '.md-blockquote': {
        borderLeft: '3px solid rgba(255, 255, 255, 0.4)',
        padding: '1em 1.5em',
        margin: '1.5em 0',
        background: 'rgba(255, 255, 255, 0.05)',
        borderRadius: '0 12px 12px 0',
        color: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(10px)',
        boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.1)',
      },
      '.md-strong': {
        color: 'var(--card-color-primary)',
        fontWeight: 600,
        textShadow: '0 0 20px rgba(0, 122, 255, 0.5)',
        background: 'linear-gradient(135deg, #007aff, #5856d6)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
      },
      '.md-em': {
        color: 'var(--card-color-secondary)',
        fontStyle: 'italic',
        textShadow: '0 0 15px rgba(88, 86, 214, 0.4)',
      },
      '.md-hr': {
        border: 'none',
        height: '1px',
        background: 'linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.4), transparent)',
        margin: '2em 0',
        boxShadow: '0 1px 0 rgba(255, 255, 255, 0.1)',
      },
      'h1, h2, h3': {
        background: 'linear-gradient(135deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.7))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
        textShadow: '0 0 30px rgba(255, 255, 255, 0.3)',
        fontWeight: 200,
        letterSpacing: '0.5px',
      },
      'p': {
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: 300,
      },
      'code': {
        background: 'rgba(255, 255, 255, 0.1)',
        color: 'rgba(255, 255, 255, 0.9)',
        padding: '3px 8px',
        borderRadius: '6px',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        backdropFilter: 'blur(10px)',
        fontFamily: 'SF Mono, Monaco, monospace',
        fontSize: '0.9em',
      },
    },
  },
};

// 温暖主题
export const warmTheme: ThemeConfig = {
  id: '温暖',
  name: '温暖',
  description: '温馨舒适的暖色主题',
  font: {
    family: 'Georgia, "Times New Roman", serif',
    size: 15,
    lineHeight: 1.8,
    weight: 400,
  },
  colors: {
    primary: '#e67e22',
    secondary: '#f39c12',
    accent: '#d35400',
    text: '#5d4037',
    background: '#fdf6e3',
    border: 'rgba(230, 126, 34, 0.2)',
  },
  spacing: {
    padding: 28,
    margin: 12,
    borderRadius: 24,
  },
  background: {
    type: 'gradient',
    gradientDirection: 45,
    gradientStart: '#fff8e1',
    gradientEnd: '#ffe0b2',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(230, 126, 34, 0.2)',
    blur: 30,
    spread: 0,
    offsetX: 0,
    offsetY: 15,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      overflow: 'hidden',
      '&::before': {
        content: '"☀️"',
        position: 'absolute',
        top: '15px',
        right: '15px',
        fontSize: '24px',
        zIndex: 2,
        animation: 'warmGlow 4s ease-in-out infinite',
      },
      '&::after': {
        content: '""',
        position: 'absolute',
        top: '-100px',
        left: '-100px',
        width: '200px',
        height: '200px',
        borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(230, 126, 34, 0.1) 0%, transparent 70%)',
        filter: 'blur(60px)',
        zIndex: 0,
      },
    },
    elements: {
      '.card-content': {
        position: 'relative',
        borderRadius: '24px',
        padding: '32px',
        background: 'rgba(255, 255, 255, 0.9)',
        border: '2px solid rgba(230, 126, 34, 0.15)',
        height: '100%',
        color: 'var(--card-color-text)',
        zIndex: 1,
        boxShadow: 'inset 0 2px 0 rgba(255, 255, 255, 0.8), 0 0 40px rgba(230, 126, 34, 0.1)',
        '&::before': {
          content: '""',
          position: 'absolute',
          top: '0',
          left: '50%',
          transform: 'translateX(-50%)',
          width: '60px',
          height: '4px',
          background: 'linear-gradient(90deg, var(--card-color-primary), var(--card-color-secondary))',
          borderRadius: '0 0 4px 4px',
        },
      },
      '.md-blockquote': {
        borderLeft: '4px solid var(--card-color-primary)',
        padding: '1.2em 1.8em',
        margin: '1.5em 0',
        background: 'linear-gradient(90deg, rgba(230, 126, 34, 0.08), rgba(230, 126, 34, 0.03))',
        borderRadius: '0 16px 16px 0',
        color: '#6d4c41',
        fontStyle: 'italic',
        position: 'relative',
        '&::before': {
          content: '"💭"',
          position: 'absolute',
          left: '-8px',
          top: '8px',
          fontSize: '16px',
          background: 'white',
          borderRadius: '50%',
          width: '24px',
          height: '24px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          boxShadow: '0 2px 8px rgba(230, 126, 34, 0.2)',
        },
      },
      '.md-strong': {
        color: 'var(--card-color-primary)',
        fontWeight: 700,
        background: 'linear-gradient(135deg, var(--card-color-primary), var(--card-color-secondary))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
        textShadow: '0 2px 4px rgba(230, 126, 34, 0.1)',
      },
      '.md-em': {
        color: 'var(--card-color-secondary)',
        fontStyle: 'italic',
        background: 'linear-gradient(120deg, transparent 0%, rgba(243, 156, 18, 0.1) 50%, transparent 100%)',
        padding: '0 4px',
        borderRadius: '4px',
      },
      '.md-hr': {
        border: 'none',
        height: '2px',
        background: 'linear-gradient(90deg, transparent, var(--card-color-primary), var(--card-color-secondary), transparent)',
        margin: '2.5em 0',
        borderRadius: '1px',
        position: 'relative',
        '&::after': {
          content: '"🌸"',
          position: 'absolute',
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
          background: 'white',
          padding: '4px 8px',
          borderRadius: '12px',
          fontSize: '14px',
          boxShadow: '0 2px 8px rgba(230, 126, 34, 0.1)',
        },
      },
      'h1, h2, h3': {
        background: 'linear-gradient(135deg, var(--card-color-primary), var(--card-color-secondary))',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
        fontFamily: 'Georgia, serif',
        fontWeight: 600,
        letterSpacing: '0.3px',
        marginBottom: '0.8em',
        position: 'relative',
        '&::after': {
          content: '""',
          position: 'absolute',
          bottom: '-8px',
          left: '0',
          width: '40px',
          height: '2px',
          background: 'linear-gradient(90deg, var(--card-color-primary), transparent)',
          borderRadius: '1px',
        },
      },
      'p': {
        color: 'var(--card-color-text)',
        lineHeight: 1.8,
        marginBottom: '1.2em',
      },
      'code': {
        background: 'rgba(230, 126, 34, 0.1)',
        color: 'var(--card-color-accent)',
        padding: '3px 8px',
        borderRadius: '8px',
        border: '1px solid rgba(230, 126, 34, 0.2)',
        fontFamily: 'Monaco, "Courier New", monospace',
        fontSize: '0.9em',
      },
      'ul, ol': {
        paddingLeft: '1.5em',
        '& li': {
          marginBottom: '0.5em',
          '&::marker': {
            color: 'var(--card-color-primary)',
          },
        },
      },
    },
  },
};

// 自然纹理主题
export const natureTheme: ThemeConfig = {
  id: '自然',
  name: '自然',
  description: '清新自然的纹理背景主题',
  font: {
    family: 'Georgia, "Times New Roman", serif',
    size: 16,
    lineHeight: 1.6,
    weight: 400,
  },
  colors: {
    primary: '#2e7d32',
    secondary: '#388e3c',
    accent: '#66bb6a',
    text: '#1b5e20',
    background: '#e8f5e8',
    border: 'rgba(46, 125, 50, 0.2)',
  },
  spacing: {
    padding: 32,
    margin: 16,
    borderRadius: 20,
  },
  background: {
    type: 'texture',
    texturePattern: 'nature-field',
    opacity: 85,
    textOverlay: 'semi-transparent',
    contrastBoost: 15,
    blurAmount: 0,
  },
  shadow: {
    enabled: true,
    color: 'rgba(46, 125, 50, 0.25)',
    blur: 20,
    spread: 0,
    offsetX: 0,
    offsetY: 10,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      overflow: 'hidden',
    },
    elements: {
      '.card-content': {
        position: 'relative',
        borderRadius: '20px',
        padding: '36px',
        background: 'rgba(255, 255, 255, 0.92)',
        border: '1px solid rgba(46, 125, 50, 0.15)',
        backdropFilter: 'blur(12px)',
        height: '100%',
        zIndex: 2,
        boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.8)',
      },
      '.md-blockquote': {
        borderLeft: '4px solid var(--card-color-primary)',
        padding: '1.2em 1.8em',
        margin: '1.5em 0',
        background: 'rgba(46, 125, 50, 0.08)',
        borderRadius: '0 12px 12px 0',
        color: '#2e7d32',
        fontStyle: 'italic',
        position: 'relative',
        '&::before': {
          content: '"🌿"',
          position: 'absolute',
          left: '-10px',
          top: '12px',
          fontSize: '18px',
          background: 'white',
          borderRadius: '50%',
          width: '28px',
          height: '28px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          boxShadow: '0 2px 8px rgba(46, 125, 50, 0.2)',
        },
      },
      '.md-strong': {
        color: 'var(--card-color-primary)',
        fontWeight: 700,
      },
      '.md-em': {
        color: 'var(--card-color-secondary)',
        fontStyle: 'italic',
        background: 'linear-gradient(120deg, transparent 0%, rgba(46, 125, 50, 0.1) 50%, transparent 100%)',
        padding: '0 4px',
        borderRadius: '4px',
      },
      'h1, h2, h3': {
        color: 'var(--card-color-primary)',
        fontWeight: 600,
        marginBottom: '1em',
        position: 'relative',
        '&::after': {
          content: '""',
          position: 'absolute',
          bottom: '-8px',
          left: '0',
          width: '50px',
          height: '2px',
          background: 'linear-gradient(90deg, var(--card-color-primary), var(--card-color-accent))',
          borderRadius: '1px',
        },
      },
      'p': {
        color: 'var(--card-color-text)',
        lineHeight: 1.7,
        marginBottom: '1.2em',
      },
    },
  },
};

// Apple Notes Theme
export const appleNotesTheme: ThemeConfig = {
  id: 'AppleNotes',
  name: 'Apple Notes',
  description: 'Inspired by Apple Notes: clean, modern, and elegant.',
  font: {
    family: 'SF Pro Text, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Arial, sans-serif',
    size: 16,
    lineHeight: 1.7,
    weight: 400,
  },
  colors: {
    primary: '#FFD600', // Apple yellow
    secondary: '#FFAB00',
    accent: '#FFF9C4',
    text: '#222',
    background: '#FAFAF7',
    border: 'rgba(0,0,0,0.08)',
  },
  spacing: {
    padding: 28,
    margin: 16,
    borderRadius: 18,
  },
  background: {
    type: 'solid',
    solidColor: '#FAFAF7',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(0,0,0,0.08)',
    blur: 24,
    spread: 0,
    offsetX: 0,
    offsetY: 8,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      background: '#FAFAF7',
      borderRadius: '18px',
      boxShadow: '0 4px 24px 0 rgba(0,0,0,0.08)',
      border: '1px solid rgba(0,0,0,0.08)',
      overflow: 'hidden',
    },
    elements: {
      '.card-content': {
        background: '#FFF',
        borderRadius: '16px',
        padding: '32px',
        border: '1px solid #F5F5F5',
        boxShadow: '0 1px 4px 0 rgba(0,0,0,0.03)',
        minHeight: '200px',
      },
      '.md-blockquote': {
        borderLeft: '4px solid #FFD600',
        padding: '1em 1.5em',
        margin: '1.5em 0',
        background: 'rgba(255, 214, 0, 0.08)',
        borderRadius: '0 8px 8px 0',
        color: '#555',
        fontStyle: 'italic',
      },
      '.md-strong': {
        color: '#FFD600',
        fontWeight: 700,
      },
      '.md-em': {
        color: '#FFAB00',
        fontStyle: 'italic',
        background: 'rgba(255, 214, 0, 0.10)',
        borderRadius: '4px',
        padding: '0 4px',
      },
      'h1, h2, h3': {
        color: '#222',
        fontWeight: 700,
        marginBottom: '1em',
      },
      'p': {
        color: '#222',
        lineHeight: 1.7,
        marginBottom: '1.2em',
      },
    },
  },
};

// Apple Notes Dark Theme
export const appleNotesDarkTheme: ThemeConfig = {
  id: 'AppleNotesDark',
  name: 'Apple Notes Dark',
  description: 'Apple Notes inspired dark mode: minimal, professional, and native macOS look.',
  font: {
    family: '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Arial, sans-serif',
    size: 16,
    lineHeight: 1.7,
    weight: 400,
  },
  colors: {
    primary: '#FFD600', // Apple yellow accent
    secondary: '#FFAB00',
    accent: '#33323a',
    text: '#f5f5f7',
    background: '#1c1c1e',
    border: 'rgba(255,255,255,0.08)',
  },
  spacing: {
    padding: 28,
    margin: 16,
    borderRadius: 18,
  },
  background: {
    type: 'solid',
    solidColor: '#1c1c1e',
    opacity: 100,
  },
  shadow: {
    enabled: true,
    color: 'rgba(0,0,0,0.5)',
    blur: 32,
    spread: 0,
    offsetX: 0,
    offsetY: 12,
  },
  layout: {
    width: 440,
    height: 586,
    viewMode: '长卡片',
    hideOverflow: false,
    showPageNumbers: false,
    layoutMode: '自动拆分',
    scale: 100,
  },
  customStyles: {
    container: {
      position: 'relative',
      background: '#1c1c1e',
      borderRadius: '18px',
      boxShadow: '0 6px 32px 0 rgba(0,0,0,0.5)',
      border: '1px solid rgba(255,255,255,0.08)',
      overflow: 'hidden',
    },
    elements: {
      '.card-content': {
        background: '#232326',
        borderRadius: '16px',
        padding: '32px',
        border: '1px solid #232326',
        boxShadow: '0 1px 4px 0 rgba(0,0,0,0.10)',
        minHeight: '200px',
      },
      'h1': {
        color: '#FFD600',
        fontWeight: 700,
        fontSize: '2.1em',
        marginBottom: '0.7em',
        marginTop: 0,
        letterSpacing: '-0.01em',
      },
      'h2, h3': {
        color: '#f5f5f7',
        fontWeight: 600,
        background: 'linear-gradient(90deg, #FFD600 0%, #FFAB00 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        backgroundClip: 'text',
        marginTop: '1.5em',
        marginBottom: '0.7em',
      },
      'p': {
        color: '#f5f5f7',
        lineHeight: 1.7,
        marginBottom: '1.2em',
        marginTop: 0,
      },
      'ul, ol': {
        margin: '1.2em 0',
        paddingLeft: '1.5em',
      },
      'li': {
        marginBottom: '0.5em',
        color: '#f5f5f7',
      },
      'img': {
        display: 'block',
        maxWidth: '100%',
        borderRadius: '12px',
        margin: '1.2em 0',
        boxShadow: '0 2px 8px rgba(0,0,0,0.18)',
      },
      '.md-blockquote': {
        borderLeft: '4px solid #FFD600',
        padding: '1em 1.5em',
        margin: '1.5em 0',
        background: 'rgba(255, 214, 0, 0.08)',
        borderRadius: '0 8px 8px 0',
        color: '#e0e0e0',
        fontStyle: 'italic',
      },
      '.md-strong': {
        color: '#FFD600',
        fontWeight: 700,
      },
      '.md-em': {
        color: '#FFAB00',
        fontStyle: 'italic',
        background: 'rgba(255, 214, 0, 0.10)',
        borderRadius: '4px',
        padding: '0 4px',
      },
      '.md-codespan, code, pre': {
        background: '#232326',
        color: '#FFD600',
        fontFamily: 'SFMono-Regular, Menlo, Monaco, Consolas, monospace',
        fontSize: '0.98em',
        borderRadius: '5px',
        padding: '0.18em 0.5em',
        margin: '0 0.2em',
        boxShadow: '0 1px 2px rgba(0,0,0,0.10)',
      },
    },
  },
};

// 主题注册表
export const predefinedThemes = {
  [defaultTheme.id]: defaultTheme,
  [darkTheme.id]: darkTheme,
  [glassTheme.id]: glassTheme,
  [warmTheme.id]: warmTheme,
  [natureTheme.id]: natureTheme,
  [appleNotesTheme.id]: appleNotesTheme,
  [appleNotesDarkTheme.id]: appleNotesDarkTheme,
};